version: '3'
services:
   jenkins:    #web yerine hersey gelebilir 
      container_name: jenkins # --name yerine
      ports: # -p yerine
        - "8080:8080"
      build: .
      networks:
         - net
      volumes:
      - "$HOME/Desktop/volumes/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks: 
   net: 
